#!/usr/bin/env python3
"""Derive the two ibex_top filelists (upstream SV lane, Arch lane) from the
fusesoc-resolved Verilator command file the test harness produces.

Usage:
    python3 flow/make_filelists.py <path/to/lowrisc_ibex_ibex_top_tracing_0.1.vc>

The .vc lives under a fusesoc build tree whose `src/` directory holds
*copies* of files from $IBEX_ROOT. Each copy is mapped back to its origin
under $IBEX_ROOT by basename + content hash, and written with an
`${IBEX_ROOT}` prefix so the lists are reproducible on any checkout.
Lint-waiver (.vlt) lines are dropped; `--top-module`, `--exe`, `-G` and
`-CFLAGS` lines are dropped; `+incdir+` and `-D` lines are kept (incdirs
mapped the same way, `-D` verbatim).

Outputs (overwritten):
    flow/ibex_top_sv.f    upstream Ibex only
    flow/ibex_top_arch.f  upstream minus the 18 ported modules, plus build/*.sv
                          (package first), written with a ${REPO_ROOT} prefix
"""
import hashlib, os, sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
IBEX_ROOT = Path(os.environ.get("IBEX_ROOT", Path.home() / "github" / "ibex")).resolve()
PORTED = {f"ibex_{m}.sv" for m in (
    "alu compressed_decoder controller core counter decoder ex_block fetch_fifo icache "
    "id_stage if_stage load_store_unit multdiv_fast pmp prefetch_buffer register_file_ff "
    "top wb_stage").split()}

# Simulation-only sources that sit ABOVE ibex_top (tracing wrapper) and are not
# synthesisable; lowRISC's own syn/ flow skips them as well.
SIM_ONLY = {"ibex_tracer.sv", "ibex_tracer_pkg.sv", "ibex_top_tracing.sv"}
# Pad / IO primitives that the fusesoc lint tree drags in but ibex_top never
# instantiates; prim_usb_diff_rx uses drive-strength assigns (`assign (weak0,
# pull1) ...`) that Yosys cannot parse. Excluding them changes nothing that is
# synthesised (hierarchy -top ibex_top would discard them anyway).
SIM_ONLY |= {"prim_usb_diff_rx.sv", "prim_pad_wrapper.sv", "prim_pad_attr.sv"}

def md5(p: Path) -> str:
    return hashlib.md5(p.read_bytes()).hexdigest()

def index_ibex() -> dict:
    idx = {}
    for sub in ("rtl", "vendor", "shared", "dv"):
        for p in (IBEX_ROOT / sub).rglob("*"):
            if p.is_file() and p.suffix in (".sv", ".svh", ".v", ".vh"):
                idx.setdefault(p.name, []).append(p)
    return idx

def main(vc: Path) -> None:
    build_dir = vc.parent
    idx = index_ibex()
    sv_lines, incdirs, defines = [], [], []
    unmapped = []
    for raw in vc.read_text().splitlines():
        s = raw.strip()
        if not s or s.startswith("--") or s.startswith("-G") or s.startswith("-CFLAGS"):
            continue  # tool options (--top-module, --exe, --Mdir, ...) are not part of the filelist
        if s.startswith("+incdir+"):
            d = (build_dir / s[len("+incdir+"):]).resolve()
            # map the incdir by mapping any file inside it
            mapped = None
            for f in d.iterdir():
                cands = [c for c in idx.get(f.name, []) if c.is_file() and md5(c) == md5(f)]
                if cands:
                    mapped = cands[0].parent
                    break
            if mapped is None:
                unmapped.append(s); continue
            incdirs.append("+incdir+${IBEX_ROOT}/" + str(mapped.relative_to(IBEX_ROOT)))
            continue
        if s.startswith("-D"):
            # RVFI=1 comes from the simulation harness (ibex_top_tracing). The
            # ARCH port ties every RVFI output to 0 (specs note N-1) while
            # upstream would add real trace-tracking logic under `ifdef RVFI`;
            # synthesising both lanes without RVFI keeps the compared logic equal.
            if s.startswith("-DRVFI"):
                continue
            defines.append(s); continue
        if s.endswith(".vlt"):
            continue
        if s.endswith(".sv") or s.endswith(".v"):
            f = (build_dir / s).resolve()
            if f.name in SIM_ONLY:
                continue
            cands = [c for c in idx.get(f.name, []) if md5(c) == md5(f)]
            if not cands:
                unmapped.append(s); continue
            sv_lines.append("${IBEX_ROOT}/" + str(cands[0].relative_to(IBEX_ROOT)))
            continue
        unmapped.append(s)
    if unmapped:
        sys.exit("unmapped entries:\n  " + "\n  ".join(unmapped))
    hdr = ["# generated by flow/make_filelists.py from the harness's fusesoc .vc; do not edit",
           f"# IBEX_ROOT commit: {os.popen(f'git -C {IBEX_ROOT} rev-parse HEAD').read().strip()}"]
    (REPO_ROOT / "flow/ibex_top_sv.f").write_text("\n".join(hdr + defines + incdirs + sv_lines) + "\n")
    arch_lines = [l for l in sv_lines if Path(l).name not in PORTED]
    build = sorted((REPO_ROOT / "build").glob("*.sv"))
    pkgs = [p for p in build if p.name.endswith("_pkg.sv")]
    rest = [p for p in build if not p.name.endswith("_pkg.sv")]
    arch_lines += ["${REPO_ROOT}/build/" + p.name for p in pkgs + rest]
    (REPO_ROOT / "flow/ibex_top_arch.f").write_text("\n".join(hdr + defines + incdirs + arch_lines) + "\n")
    print(f"sv lane: {len(sv_lines)} files, arch lane: {len(arch_lines)} files, {len(incdirs)} incdirs, {len(defines)} defines")

if __name__ == "__main__":
    main(Path(sys.argv[1]).resolve())
